---
- hosts: tag_Project_master
  become: yes
  tasks:
    - name: Get join token
      become: yes
      become_user: ubuntu
      command: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file
      delegate_to: localhost
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: /tmp/kubernetes_join_command
        mode: '0777'


