apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-operator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ZackZhouHB/zack-gitops-project'
    targetRevision: editing
    path: postgresql-operator/kustomize  # The root path of the master kustomization.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
