# docker-compose.yml
version: '3'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile-user
    ports:
      - "5001:5001"
  order-service:
    build:
      context: .
      dockerfile: Dockerfile-order
    ports:
      - "5002:5002"