apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-efs-pv-root
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0cf56687c9ae73aa6
