version: '3'
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  user-service:
    build:
      context: ./user_service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./order_service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5002:5002"

  api-gateway:
    build:
      context: ./api_gateway
    depends_on:
      - consul
      - user-service
      - order-service
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5000:5000"
