apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zackweb
  namespace: argocd
spec:
  destination:
    namespace: 'zackweb'
    server: 'https://kubernetes.default.svc'
  source:
    path: eks-deploy
    repoURL: 'https://github.com/ZackZhouHB/zack-gitops-project'
    targetRevision: editing
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
