apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zack-web
spec:
  destination:
    name: ''
    namespace: zackapp
    server: 'https://kubernetes.default.svc'
  source:
    path: /argocd-initialdeploy
    repoURL: 'https://github.com/ZackZhouHB/zack-gitops-project'
    targetRevision: editing
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
