apiVersion: apps/v1
kind: Deployment
metadata:
  name: zackweb
  labels:
    app: zackweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zackweb
  template:
    metadata:
      labels:
        app: zackweb
    spec:
      containers:
      - name: zackweb
        image: zackz001/gitops-jekyll:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: zackweb-service
spec:
  selector:
    app: zackweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zackweb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: aws.zackdevops.online  # Replace with your domain
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: zackweb-service
              port:
                number: 80

