version: '3'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile-user
    ports:
      - "5001:5001"
  order-service:
    build:
      context: .
      dockerfile: Dockerfile-order
    ports:
      - "5002:5002"
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    ports:
      - "5000:5000"

# docker-compose up --build

# docker run -d --name=consul -p 8500:8500 consul

# without api gateway
#      http://localhost:5001/users
#      http://localhost:5002/orders

# with API gateway
#    http://localhost:5000/users
#    http://localhost:5000/orders