version: '3'
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul:8500"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  user-service:
    build:
      context: ./user_service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_USERSERVICE_RULE=PathPrefix(`/users`)
      - TRAEFIK_HTTP_SERVICES_USERSERVICE_LOADBALANCER_SERVERSCHEME=http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/users`)"
      - "traefik.http.services.user-service.loadbalancer.server.port=5001"
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./order_service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_ORDERSERVICE_RULE=PathPrefix(`/orders`)
      - TRAEFIK_HTTP_SERVICES_ORDERSERVICE_LOADBALANCER_SERVERSCHEME=http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order-service.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.order-service.loadbalancer.server.port=5002"
    ports:
      - "5002:5002"

  api-gateway:
    build:
      context: ./api_gateway
    depends_on:
      - consul
      - user-service
      - order-service
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=5000"
    ports:
      - "5000:5000"
