version: '3'
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul:8500"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - consul
    networks:
      - web

  user-service:
    build:
      context: .
      dockerfile: Dockerfile-user
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/users`)"
      - "traefik.http.services.user-service.loadbalancer.server.port=5001"
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5001:5001"
    networks:
      - web

  order-service:
    build:
      context: .
      dockerfile: Dockerfile-order
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order-service.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.order-service.loadbalancer.server.port=5002"
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5002:5002"
    networks:
      - web

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=5000"
    depends_on:
      - consul
      - user-service
      - order-service
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    external: true
