---
- name: Install Python 3 and pip3, and install boto3 package
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install boto3 package
      pip:
        name: boto3

- name: Configure Ansible
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update ansible.cfg
      blockinfile:
        path: /etc/ansible/ansible.cfg
        block: |
          [defaults]
          inventory = /home/ubuntu/aws_ec2.yaml

          [inventory]
          enable_plugins = aws_ec2

          [ssh_connection]
          ssh_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

          remote_user = ubuntu
          private_key_file = /home/ubuntu/terraform-new-key1.pem
      create: yes
      backup: yes