---
- name: cron
  hosts: test
  tasks:
  - name: Creates a cron file under /etc/cron.d
    ansible.builtin.cron:
      name: yum autoupdate
      minute: "*/2"
      user: natasha
      job: 'logger "EX200 inprogress"'

