---
- name: hardware report
  hosts: all
  tasks:
  - name: Copy file 
    ansible.builtin.get_url:
      url: http://classroom/materials/hwreport.empty
      dest: /root/hwreport.txt

  - name: hostname
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: '^HOST='
      line: "HOST={{ inventory_hostname }}"
  - name: memory
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: '^MEMORY='
      line: "MEMORY={{ ansible_memtotal_mb }}"
  - name: bios
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: '^BIOS='
      line: "BIOS={{ ansible_bios_version }}"
  - name: vda
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: '^DISK_SIZE_VDA='
      line: "DISK_SIZE_VDA={{ ansible_devices.vda.size }}"
  - name: hostname
    ansible.builtin.lineinfile:
      path: /root/hwreport.txt
      regexp: '^DISK_SIZE_VDB='
      line: "DISK_SIZE_VDB={{ ansible_devices.vdb.size | default('NONE', true) }}"
