---
- name: lv
  hosts: all
  tasks:
  - block:
    - name: Create a logical volume of 1500m
      community.general.lvol:
        vg: research
        lv: data
        size: 1500

    - name: Create a ext4 filesystem on /dev/sdb1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data

    rescue:
    - name: Create a logical volume of 800m
      community.general.lvol:
        vg: research
        lv: data
        size: 800
                
    - name: Create a ext4 filesystem on /dev/sdb1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data

  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: Could not create logical volume of that size
    when: ansible_lvm.vgs.research is defined

  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: Volume group done not exist
    when: ansible_lvm.vgs.research is not defined
