---
- name: Install a list of 
  hosts: dev,test,prod
  tasks:
  - ansible.builtin.yum:
      name:
        - php
        - mariadb
      state: present


- name: Upgrade all packages
  hosts: dev
  tasks:
  - ansible.builtin.yum:
      name: '*'
      state: latest


- name: Install the 'Development tools' package group
  hosts: dev
  tasks:
  - ansible.builtin.yum:
      name: "@RPM Development Tools"
      state: present

