---
- name: u1
  hosts: dev,test
  vars_files:
  - /home/greg/ansible/locker.yml
  - /home/greg/ansible/user_list.yml
  tasks:
  - name: group1
    ansible.builtin.group:
      name: devops
      state: present

  - name: Set u1
    ansible.builtin.user:
      name: "{{ item.name }}"
      password_expire_max: "{{ item.password_expire_max }}"
      groups: devops
      password: "{{ pw_developer | password_hash('sha512') }}" 
      uid: "{{ item.uid }}"
    loop: "{{ users}}"  
    when: item.job == 'developer'

- name: u2
  hosts: prod
  vars_files:
  - /home/greg/ansible/locker.yml
  - /home/greg/ansible/user_list.yml
  tasks:
  - name: group2  
    ansible.builtin.group:
      name: opsmgr
      state: present

  - name: Set u2        
    ansible.builtin.user:   
      name: "{{ item.name }}"
      password_expire_max: "{{ item.password_expire_max }}"   
      groups: opsmgr    
      password: "{{ pw_manager | password_hash('sha512') }}" 
      uid: "{{ item.uid }}" 
    loop: "{{ users}}"      
    when: item.job == 'manager'    
