apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
  volumeName: openwebui-efs-pv
