apiVersion: v1
kind: Pod
metadata:
  name: efs-utility
  namespace: default
spec:
  containers:
  - name: utility
    image: alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: efs-volume
      mountPath: /efs
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: target-efs-pvc-root
  restartPolicy: Never
