---

- hosts: tag_KK_ubt
  become: yes
  gather_facts: yes

  tasks:

    - name: Fetch FQDN
      shell: "FQDN=$(curl -s http://169.254.169.254/latest/meta-data/local-hostname) && echo $FQDN"
      register: fqdn_output

    - name: Set hostname
      hostname:
        name: "{{ fqdn_output.stdout }}"

    - name: Create CRI-O config file
      file:
        path: "/etc/modules-load.d/crio.conf"
        state: touch

    - name: Add modules in conf file
      blockinfile:
        path: "/etc/modules-load.d/crio.conf"
        block: |
          overlay
          br_netfilter

    - name: Enable sysctl params
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: touch

    - name: Add configuration
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Load kernel modules overlay and br_netfilter
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Reload parameters
      command: sudo sysctl --system

    - name: Disable swap
      shell: |
              sudo swapoff -a

    - name: Comment out swap entry in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*'
        line: '#\g<0>'
        backup: yes

    - name: Install required packages
      apt:
        name:
          - lrzsz
          - curl
        update_cache: yes
        state: present

    - name: Enable CRI-O repository
      environment:
         OS: xUbuntu_22.04
         VERSION: 1.28
      shell: |
               echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
               echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
               curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
               curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -

    - name: Update apt package cache
      command: apt-get update
      become: yes

    - name: Install CRI-O and CRI-O tools
      command: apt-get install -y cri-o cri-o-runc cri-tools
      become: yes

    - name: Enable and start CRI-O service
      systemd:
        name: crio
        enabled: yes
        state: started

    - name: Install Kubernetes dependencies
      apt:
        name:
          - apt-transport-https
        state: present

    - name: Create kubernetes repo file
      file:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        state: "touch"

    - name: Add K8s Source
      blockinfile:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        block: |
              deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: Install Kubernetes components
      shell: |
              curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
              sudo apt-get update
              sudo apt-get install -y kubelet=1.28.1-00 kubeadm=1.28.1-00 kubectl=1.28.1-00
              sudo apt-mark hold kubelet kubeadm kubectl

    - name: Reboot the system
      reboot:
        reboot_timeout: 300

