---
- hosts: tag_Project_master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: sudo kubeadm init --pod-network-cidr=192.168.0.0/16  --cri-socket=/var/run/crio/crio.sock  --ignore-preflight-errors Swap >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu

    - name: Install Calico Pod network
      become: yes
      become_user: ubuntu
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Get join token
      become: yes
      become_user: ubuntu
      command: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file
      delegate_to: localhost
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: /tmp/kubernetes_join_command
        mode: '0777'

