---
- name: Fetch content from file on Kubernetes master
  hosts: tag_Project_master
  become: yes
  tasks:
    - name: Fetch content from file
      ansible.builtin.fetch:
        src: /home/ubuntu/.kube/config
        dest: /tmp/fetched_file
        flat: yes
- name: Install kubectl on Ansible control node
  hosts: localhost  # Run the task on the Ansible control node
  gather_facts: no  # Skip gathering facts

  tasks:
    #    - name: Install kubectl
    #  become: yes  # Run the command with elevated privileges if required
    #  command: curl -LO https://dl.k8s.io/release/v1.23.2/bin/linux/amd64/kubectl && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: enabl kubectl
      become_user: ubuntu  # Run the command with elevated privileges if required
      command: mkdir /home/ubuntu/.kube
      ignore_errors: yes
    - name: copy admin.config
      become: yes  # Run the command with elevated privileges if required
      command: cp /tmp/fetched_file /home/ubuntu/.kube/config
