apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-langchain-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0cf56687c9ae73aa6  # RAG Shared Storage EFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-langchain-pvc
  namespace: langchain
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
