apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-service-account
  namespace: langchain
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::615299759525:role/eks-rag-weaviate-rag-backend-role
