apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded values from ~/.aws/credentials
  AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxxxxxx"
  AWS_SECRET_ACCESS_KEY: "Vxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  AWS_REGION: "YXAtc291dGhlYXN0LTI="  # ap-southeast-2
