apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwebui-sa
  namespace: openwebui
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::615299759525:role/eks-rag-weaviate-rag-backend-role
