version: '3.8'
services:
  backend:
    image: pneumonia-classifier-1
    ports:
      - "5000:5000"
    networks:
      - pneumonia-net

  frontend:
    image: pneumonia-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - pneumonia-net

networks:
  pneumonia-net:
    driver: bridge