name: Deploy CloudFormation Stack

on: 
  push: 
    branches:
      - main
      - editing
    paths:             # any change in folder "zack_blog" 
      - cloudformation/**   # for both stage and main, will trigger workflow
  
  pull_request:        # no one can commit to main except approvel needed from main branch owner
    branches:          # raise pull_request when merge from stage to main
      - main           # will trigger workflow
    paths:          
      - cloudformation/**

env:                   # cred for AWS access, terrform is looking for      
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/cf-zackblog.yaml \
          --stack-name zackblog-cloudformation-stack \
          --capabilities CAPABILITY_NAMED_IAM
