name: "zack gitops workflow for EC2 docker web-deployment"
on: 
  push: 
    branches:
      - main
    paths:             # any change in folder "zack_blog" 
      - zack_blog/**   # for both stage and main, will trigger workflow
  
  pull_request:        # no one can commit to main except approvel needed from main branch owner
    branches:          # raise pull_request when merge from stage to main
      - main           # will trigger workflow
    paths:          
      - zack_blog/**

env:                  
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_NAME: ${{secrets.HOST_NAME}}
  USER_NAME: ${{secrets.USER_NAME}}


jobs: 
  terraform:   # create a ubuntu container, cd to terraform dir, checkout source code
    name: "EC2 docker web depolyment"
    runs-on: ubuntu-latest    # from github runners containers 
    defaults:
      run:
        shell: bash
        working-directory: ./zack_blog
    
    steps:

      - name: SCM checkout
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_NAME}}
          username: ${{secrets.USER_NAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo usermod -aG docker ubuntu
            sudo docker stop $(docker ps -a -q)
            sudo docker rm $(docker ps -a -q)        
            sudo docker pull zackz001/gitops-jekyll:v${{ github.run_number }}
            sudo docker run -d -p 80:80 zackz001/gitops-jekyll:v${{ github.run_number }}
            sudo docker run -d --restart unless-stopped -p 80:80 zackz001/gitops-jekyll:v${{ github.run_number }})
            
