name: " Deploy to EC2 "

on:
  push:
    branches:
      - main
      - editing
    paths:             # any change in folder "zack_blog" 
      - zack_blog/**   # for both stage and main, will trigger workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to EC2
      run: scp -r _site/* ec2-user@54.79.79.80:/usr/share/nginx/html

