name: "zack gitops workflow for blog CI image build"
on: 
  push: 
    branches:
      - main
      - editing
    paths:             # any change in folder "zack_blog" 
      - zack_blog/**   # for both stage and main, will trigger workflow
  
  pull_request:        # no one can commit to main except approvel needed from main branch owner
    branches:          # raise pull_request when merge from stage to main
      - main           # will trigger workflow
    paths:          
      - zack_blog/**

env:                   # cred for AWS access, terrform is looking for      
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  # also can be stored in github var
#  AWS_DEFAULT_REGION: ap-southeast-2
#  EKS_CLUSTER: zack-gitops-eks-prod

  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_NAME: ${{secrets.HOST_NAME}}
  USER_NAME: ${{secrets.USER_NAME}}


jobs: 
  terraform:   # create a ubuntu container, cd to terraform dir, checkout source code
    name: "Zackweb image build CI pipeline"
    runs-on: ubuntu-latest    # from github runners containers 
    defaults:
      run:
        shell: bash
        working-directory: ./zack_blog
    
    steps:

      - name: SCM checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          IMAGE_NAME=zackz001/gitops-jekyll
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker build -t zackz001/gitops-jekyll:test .
          docker tag zackz001/gitops-jekyll:test zackz001/gitops-jekyll:v${{ github.run_number }}  # Replace with your desired tag
          docker tag zackz001/gitops-jekyll:v${{ github.run_number }} zackz001/gitops-jekyll:latest
      - name: Push Docker image newer build
        run: docker push zackz001/gitops-jekyll:v${{ github.run_number }}

      - name: Push Docker image latest
        run: docker push zackz001/gitops-jekyll:latest

      - name: Configure AWS cli on runners
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_NAME}}
          username: ${{secrets.USER_NAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/zack-gitops-project
            git pull
            sudo systemctl stop nginx
            cd /usr/share/nginx/html && sudo rm -rf *
            sudo cp ~/zack-gitops-project/zack_blog/_site/* /usr/share/nginx/html/ -r
            sudo cp ~/zack-gitops-project/zack_blog/_site/* /var/www/html/ -r
            sudo systemctl start nginx
            aws s3 cp ~/zack-gitops-project/zack_blog/_site/* s3://zackweb-serverless/ --recursive

#            sudo docker pull zackz001/gitops-jekyll:v${{ github.run_number }}
#            sudo docker run -d -p 80:80 zackz001/gitops-jekyll:v${{ github.run_number }}
#            sudo docker run -d --restart unless-stopped -p 80:80 zackz001/gitops-jekyll:v${{ github.run_number }})
            
##