name: "zack gitops workflow for blog"
on: 
  push: 
    branches:
      - main
      - editing
    paths:             # any change in folder "terraform" 
      - zack_blog/**   # for both stage and main, will trigger workflow
  
  pull_request:        # no one can commit to main except approvel needed from main branch owner
    branches:          # raise pull_request when merge from stage to main
      - main           # will trigger workflow
    paths:          
      - zack_blog/**

env:                   # cred for AWS access, terrform is looking for      
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  # also can be stored in github var
#  AWS_DEFAULT_REGION: ap-southeast-2
#  EKS_CLUSTER: zack-gitops-eks-prod

  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}


jobs: 
  terraform:   # create a ubuntu container, cd to terraform dir, checkout source code
    name: "apply iaac code change"
    runs-on: ubuntu-latest    # from github runners containers 
    defaults:
      run:
        shell: bash
        working-directory: ./zack_blog
    
    steps:

      - name: SCM checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '2.7.4' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Install Jekyll dependencies
        run: |
          gem install bundler
          bundle install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          IMAGE_NAME=zackz001/gitops-jekyll
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:v${{ github.ref_name}}  # Replace with your desired tag

      - name: Push Docker image
        run: docker push $IMAGE_NAME:v${{ github.ref_name}}

#      - name: Configure AWS cli on runners
#        uses: aws-actions/setup-sam@v2
#       with:
#          use-installer: true

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-southeast-2

#      - name: Debug AWS Credentials
#        run: |
#          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
#         echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
#          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"


