---
- hosts: all
  become: yes
  tasks:
  
    - name: Update and install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Stop all running containers
      shell: docker stop $(docker ps -q)
      ignore_errors: true
      register: stopped_containers

    - name: Remove all stopped containers
      shell: docker rm $(docker ps -a -q)
      when: stopped_containers.rc == 0
      ignore_errors: true

    - name: Pull Docker image
      docker_image:
        name: zackz001/gitops-jekyll
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: zackblog
        image: zackz001/gitops-jekyll:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "80:80"
